### ISSUE TITLE
Consistent nonce error on api calls

### ISSUE THREAD

**Issue by svenwoldt** [premasagar/poloniex.js#4]
Hello,
for all private api calls I receive this error.
Do you know what it is?
{ error: 'Nonce must be greater than 1432733226626155. You provided 143275514332600.' }

**Comment by joosti** [comment]
Poloniex wants to make sure they receive the ajax calls in the same sequence as they were sent. In order to enforce that, they require a nonce argument that needs to be strictly increasing. The error produced indicates that they received API calls in the 'wrong' order.

The most likely scenario is that you have multiple API calls 'close' in time that were received in a different order. You could make the requests serial (wait for a call to complete before sending out another call).

**Comment by muratbeser** [comment]
it's very very late response but it also happens from the api configuration, sometimes you may need new api key.

it's like one api key per application. Because nonce requires always higher value, when first application 10, second application can be at 7 this cause a conflict. 

since poloniex.js does not have multi thread support you should generate a new api key.

**Comment by android-leha** [comment]
It is race condition. You make two private api request and the constructs in one order, but send in another order. 
On of the ways to correct this - send requests throw queue.

**Comment by anders94** [comment]
This doesn't look like an issue with `poloniex.js` and is quite old. Closing this now.
